<a href="https://colab.research.google.com/github/Jakondo/Python-for-DL-and-CV/blob/master/Ch4_Linear_Regression_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Chapter 4: Linear Regression - PyTorch
---





In [0]:
import torch
#from torch.nn import Linear
import torch.nn as nn

#Making Predictions

In [0]:
w = torch.tensor(3.0, requires_grad=True)
b = torch.tensor(1.0, requires_grad=True)

In [0]:
def forward(x):
  y = w*x +b
  return y

In [6]:
x = torch.tensor([[4], [7]])
forward(x)

tensor([[13],
        [22]], grad_fn=<AddBackward0>)

#Linear Class

In [8]:
torch.manual_seed(1) #используется для того чтобы вводимые рандомные значения не менялись
model = Linear(in_features=1, out_features=1)
print(model.bias, model.weight)

Parameter containing:
tensor([-0.4414], requires_grad=True) Parameter containing:
tensor([[0.5153]], requires_grad=True)


In [11]:
x = torch.tensor([[2.0], [3.0], [4.5]])
model(x)

tensor([[0.5891],
        [1.1044],
        [1.8773]], grad_fn=<AddmmBackward>)

#Custom Modules

In [0]:
class LR(nn.Module):
  def __init__(self, input_size, output_size):
    super().__init__()
    self.linear = nn.Linear(input_size, output_size)
  
  def forward(self, x):
    pred = self.linear(x)
    return pred

In [0]:
torch.manual_seed(1)
model = LR(1, 1)
#print(list(model.parameters()))

In [27]:
x = torch.tensor([[1.0], [1.4]])
print(model.forward(x))

tensor([[0.0739],
        [0.2800]], grad_fn=<AddmmBackward>)


#Creating Dataset